### ISSUE TITLE
protobuf 使用枚举报错

### ISSUE THREAD

**Issue by xuanziblog** [JasonXuDeveloper/JEngine#109]
测试代码如下

```
  FieldDescriptorProto descriptorProto = new FieldDescriptorProto();

            descriptorProto.type = FieldDescriptorProto.Type.TYPE_BOOL;
            string ss = "";

            using (var stream = new System.IO.MemoryStream())
            {
                ProtoTypeRegister.Register<FieldDescriptorProto>();
                ProtoBuf.Serializer.Serialize(stream, descriptorProto);
                ss = Convert.ToBase64String(stream.ToArray());
                Debug.Log(ss);
            }
            FieldDescriptorProto reg = ProtoBuf.Serializer.Deserialize(typeof(FieldDescriptorProto),new MemoryStream(Convert.FromBase64String(ss)))  as FieldDescriptorProto;
            //FieldDescriptorProto reg = ProtoBuf.Serializer.Deserialize<FieldDescriptorProto>(new MemoryStream(Convert.FromBase64String(ss)));// 这里有个方法重定向的错误，已经修改

            Debug.Log(reg.type);
```
报错如下
![image](https://user-images.githubusercontent.com/6769676/117386918-57ae8e00-af1a-11eb-9d6f-55a470d7ac1a.png)

**Comment by JasonXuDeveloper** [comment]
请提供FieldDescriptorProto

**Comment by JasonXuDeveloper** [comment]
没事了，我晚上测试

**Comment by xuanziblog** [comment]
@JasonXuDeveloper 就是工程里面test.cs里的

**Comment by xuanziblog** [comment]
@JasonXuDeveloper 静待佳音

**Comment by JasonXuDeveloper** [comment]
<img width="787" alt="iShot2021-05-07 21 35 00" src="https://user-images.githubusercontent.com/48086348/117443892-18b12480-af7c-11eb-954d-8f9e3514fed3.png">
```FieldDescriptorProto```这个在Editor下，先不说热更能否正常使用，原生都不行啊，真机下没办法运行这个代码的。

**Comment by JasonXuDeveloper** [comment]
然后你这个enum必须定义为int类型，例如：
```c#
enum Test
{
a,
b,
c
}
enum Test: System.Int32之类的
{
a,
b,
c
}
或者
```

**Comment by xuanziblog** [comment]
@JasonXuDeveloper FieldDescriptorProto消息是工程里面test.proto这个文件用工程提供的toCS工具生成的。。因为发现没法用枚举，所以看这个消息里面有个枚举就直接用这个写了测试代码来进行测试。。

**Comment by JasonXuDeveloper** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/48086348/117460531-f4f7d980-af8f-11eb-90f6-e61804783a7a.png">
这个吗，这个也没有Type.Type_BOOL的定义啊，你定义错了吧

**Comment by xuanziblog** [comment]
@JasonXuDeveloper  是这样的啊

**Comment by JasonXuDeveloper** [comment]
哦哦 我做一个看看

**Comment by JasonXuDeveloper** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/48086348/117467447-08f30980-af97-11eb-96ae-2916c623c4c0.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/48086348/117467457-0d1f2700-af97-11eb-83d9-9ce765d57aca.png">
<img width="612" alt="image" src="https://user-images.githubusercontent.com/48086348/117467508-1ad4ac80-af97-11eb-8e46-5129ec61f9bf.png">

**Comment by xuanziblog** [comment]
不是的，，我是ILruntime里用的，报错是说的ILruntime的类型没法装换为枚举，这个Label可以删了的，不影响，有个枚举就行

**Comment by JasonXuDeveloper** [comment]
我知道，我的意思是这个枚举也是null，没办法处理啊

**Comment by xuanziblog** [comment]
@JasonXuDeveloper  thank you  我明天更新看看
