### ISSUE TITLE
杰哥，不要啦，你们不要再打啦

### ISSUE THREAD

**Issue by k1104480005** [JasonXuDeveloper/JEngine#127]
1.在Menu加个快速打开热更工程.sln，会十分方便哦！这样就不用每次找文件夹去打开
2.Copy Bundle to StreamingAssets 没Log的，强迫症患者有点难受。或者打完AB包后直接弹出窗口询问是否Copy Bundle to StreamingAssets，打AB包结束后弹个窗口提示下就更舒适了
-虐人

**Comment by JasonXuDeveloper** [comment]
快速定位热更工程并打开没必要 去vs他会给你recent的 而且每个人热更工程位置也不一样 除非做个自定义
