### ISSUE TITLE
关于UImanager来个视频吧

### ISSUE THREAD

**Issue by bournes** [JasonXuDeveloper/JEngine#130]
目前的UIManager有点弱！还有0.6版本的 JUI 跟 0.5的有不同了。。需要文档

**Comment by JasonXuDeveloper** [comment]
uimanager要在0.6.3剔除了
jui有文档啊 文档网站里有写 看0.6版本的

**Comment by bournes** [comment]
那0.6.3之后有UIKIT吗？

**Comment by JasonXuDeveloper** [comment]
UI框架除了JUI都需要重构 估计要很久以后才会正式推出了
