### ISSUE TITLE
如何能整合下gf的完整游戏流程jengine 就是最好的热更新游戏框架了

### ISSUE THREAD

**Issue by bournes** [JasonXuDeveloper/JEngine#131]
github.com/EllanJiang/UnityGameFramework 这个游戏流程，jengine不知道能不能整合一下。

**Comment by JasonXuDeveloper** [comment]
可以考虑部分地方实现GF的流程 但JEngine提倡的是开箱即用轻量和简洁 所以肯定不会搞特别复杂的流程的
