### ISSUE TITLE
JBehaviour 执行频率与设置游戏的帧率不吻合

### ISSUE THREAD

**Issue by l1000965431** [JasonXuDeveloper/JEngine#154]
我现在工程设置Application.targetFrameRate = 60。只有一个JBehaviour脚本执行，Loop函数里只打印了LoopDeltaTime，JBehaviour执行频率只有30帧

**Comment by JasonXuDeveloper** [comment]
能否提供一下可以复现的测试代码

**Comment by l1000965431** [comment]
代码：
![QQ截图20210820081950](https://user-images.githubusercontent.com/3367150/130160251-26486bdb-9627-4b2d-8fb8-1ec313e41346.png)
打印：
![QQ截图20210820082006](https://user-images.githubusercontent.com/3367150/130160254-3a797111-fbf4-4e16-bcec-6d6a1d110d3d.png)

**Comment by JasonXuDeveloper** [comment]
应该测试Loop的代码在一秒内执行了多少次 而非查看LoopDeltaTime
