### ISSUE TITLE
热更工程动态添加Animator组件并赋值片段动画，动画不能正常播放，急求解决！

### ISSUE THREAD

**Issue by zhanghaigang666** [JasonXuDeveloper/JEngine#156]
热更工程代码调用方：            
```c#
           int pathId = 911001;
            GameObject go = GameObject.CreatePrimitive(PrimitiveType.Cube);
            go.name = "testCube";
            go.layer = 10;
            go.transform.localScale = new Vector3(2, 2, 1);
            go.AddComponent<Animator>();
            var testCube = go.AddComponent<TestCube>();
            testCube.Init(pathId);
```
热更工程代码类：    
```c#
    public class TestCube : MonoBehaviour {
        public void Init(int pathId) {
            gameObject.GetComponent<Animator>().runtimeAnimatorController = Resources.Load<RuntimeAnimatorController>($"Animations/{pathId}");;
        }
    }
```
这段代码，把TestCube 类放在主工程里 cube可以正常播动画，但是把TestCube 放在热更工程里就不行，没有任何报错，就是不能正常驱动动画播放

使用纯净的JENGINE v0.6.3 版本的demo 复现如下图：
![image](https://user-images.githubusercontent.com/4361811/130945612-78189674-27a1-4624-9e2d-63b400144392.png)
![image](https://user-images.githubusercontent.com/4361811/130945652-c921702a-b1b8-478c-af54-8fa1589d673a.png)

**Comment by JasonXuDeveloper** [comment]
经测试，毫无问题，请看群里留言。
以下是演示视频和测试代码

https://user-images.githubusercontent.com/48086348/131218679-3d7f4c49-2356-4e6e-87af-ef3ea91c350a.mp4

![PNG图像](https://user-images.githubusercontent.com/48086348/131218683-f326b7ee-48a6-4129-b111-df1a0662a8e3.png)

**Comment by zhanghaigang666** [comment]
刚测试了，Transform动画里面，除了Scale动画可以，Position和Rotation动画都不行

>

**Comment by zhanghaigang666** [comment]
这个问题的原因应该是MonoBehaviourAdapter中的 OnAnimatorMove()接管了Animator的动画移动逻辑，但是适配器中转给的目标热更类又未必需要实现而产生的尴尬，你看看有没有完美解决办法

**Comment by JasonXuDeveloper** [comment]
测试代码
![PNG图像](https://user-images.githubusercontent.com/48086348/131502436-f0d67461-3e1e-486e-a06d-e70998cc3b39.png)

测试效果

https://user-images.githubusercontent.com/48086348/131502469-3bdea797-25c4-4d9a-9f0f-8e46e4e2be98.mp4

**Comment by zhanghaigang666** [comment]
反馈：对于一个开启Loop time 的animator动画，不能让动画正常循环播放，希望再改进一下！

**Comment by JasonXuDeveloper** [comment]
经测试可以循环，毫无问题。

![image](https://user-images.githubusercontent.com/48086348/132094565-25a03d67-0843-4fcd-8b88-8df42be17414.png)
![image](https://user-images.githubusercontent.com/48086348/132094507-6e216764-c06e-49a4-823d-8c93f83ac234.png)
![image](https://user-images.githubusercontent.com/48086348/132094547-957dc484-f971-4895-8ba7-937377ccfa23.png)

https://user-images.githubusercontent.com/48086348/132094630-947980fc-2c83-45fc-b266-825d3d934571.mov
