### ISSUE TITLE
热更场景中使用新增Layer进行射线检测的bug

### ISSUE THREAD

**Issue by huangkumao** [JasonXuDeveloper/JEngine#169]
重现步骤
1: 新增一个Layer
2: 在热更场景中把物体加到新增的Layer中
3:使用如下代码进行射线检测
var ray = Camera.ScreenPointToRay(Input.mousePosition);
return Physics.Raycast(ray, out hit, 1000, 新增Layer);

在编辑器模式下OK, 出包安卓后检测不到.

如果在非热更场景 随便找个物体修改Layer为 新增的Layer. 问题消失!

猜测 如果新增Layer只存在(只在热更场景中使用过)热更场景中 打包时某些信息丢失了?

**Comment by JasonXuDeveloper** [comment]
新增的layer不能热更啊 这个是打包的时候带到游戏包内的 不在热更内
