### ISSUE TITLE
热更层uint和ulong报错

### ISSUE THREAD

**Issue by fansten** [JasonXuDeveloper/JEngine#198]
![image](https://user-images.githubusercontent.com/29533416/134479448-3f8c0d80-79fd-4c67-ae24-93d9a12ec281.png)

![image](https://user-images.githubusercontent.com/29533416/134479507-90337fc7-7d77-4a8c-8c54-f2dde635ff8c.png)

**Comment by JasonXuDeveloper** [comment]
做个CLR绑定就能解决

**Comment by JasonXuDeveloper** [comment]
我也手写了一次
