### ISSUE TITLE
带有fixed64字段的protobuf结构序列化失败

### ISSUE THREAD

**Issue by fansten** [JasonXuDeveloper/JEngine#199]
![image](https://user-images.githubusercontent.com/29533416/134803160-49943891-0e5a-45b3-9c82-649c9c0e669c.png)

![$%U~ST3IR_B%S2L78V1HD X](https://user-images.githubusercontent.com/29533416/134803175-6641e594-4fd0-4511-b471-172902ecb7a0.jpg)

![OG2(9ON H_ZPR6UABN~3I@O](https://user-images.githubusercontent.com/29533416/134803182-add4dccc-2798-4fa9-b46c-a474ad331270.jpg)

![5F2X03LKFRQRZ1DJT{PPELI](https://user-images.githubusercontent.com/29533416/134803188-f65e6aab-122d-4b30-9b6e-e995a4178acb.jpg)

**Comment by JasonXuDeveloper** [comment]
ILRuntime 的Bug，
```c#
[global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
```
这个标签，如果不止一个参数，就无法正常获取标签导致序列化失败，目前建议手动改一下标签，让他只有一个参数

**Comment by JasonXuDeveloper** [comment]
https://github.com/Ourpalm/ILRuntime/issues/593
