### ISSUE TITLE
List<T> add错误

### ISSUE THREAD

**Issue by qn9663** [JasonXuDeveloper/JEngine#20]
使用 class A : JBehavior, IMyInterface ,B : MyClass,IMyInterface 时候
`List<\IMyInterface > list = new List<\IMyInterface >();

list.Add(a);//error

list.Add(b);

IL_0053: callvirt System.Void System.Collections.Generic.List`1<>::Add(!0) `

应该是用了适配器引起的继承关系问题.

**Comment by JasonXuDeveloper** [comment]
class a继承了JBehaviour，请使用JBehaviour.Get方法获取

**Comment by JasonXuDeveloper** [comment]
不要用获取monobehaviour的方法去获取JBehaviour，能获取但不能强转到别的类，因为mono适配器的问题，所以需要JBehaviour提供的方法去get，就可以进行类型转换了

**Comment by JasonXuDeveloper** [comment]
代码可以使用```来显示，
例如：
```c#
代码在这里
```

**Comment by JasonXuDeveloper** [comment]
"```" + c# + "```"

**Comment by JasonXuDeveloper** [comment]
三个`+c#+三个`

**Comment by JasonXuDeveloper** [comment]
三个“`”开头，然后c#，换行，写代码，最后三个结尾

**Comment by JasonXuDeveloper** [comment]
问题已定位，等修复，今晚。

**Comment by JasonXuDeveloper** [comment]
无法解决，ILRuntime作者回应，不能用纯热更内的接口去存跨域的对象，你得在热更里创一个对象，然后复制跨域对象的值，然后再加入字典，这样一来，是可以加入和读取的，但是更改的话无法同步，需要你自己去实现
<img width="441" alt="iShot2020-11-09 17 55 07" src="https://user-images.githubusercontent.com/48086348/98509094-bc16ca80-22b4-11eb-98f9-3060de45035c.png">

**Comment by JasonXuDeveloper** [comment]
很抱歉哈，刚刚又和ILRuntime作者探讨了一下，这个问题已经解决，明天会在development分支提交这个修复。
<img width="315" alt="iShot2020-11-09 22 36 57" src="https://user-images.githubusercontent.com/48086348/98536567-1d9e5f80-22dc-11eb-9121-26f76ca9fe1f.png">

<img width="178" alt="iShot2020-11-09 22 37 49" src="https://user-images.githubusercontent.com/48086348/98536643-34dd4d00-22dc-11eb-9038-598a12d67f0a.png">
<img width="629" alt="iShot2020-11-09 22 37 45" src="https://user-images.githubusercontent.com/48086348/98536645-360e7a00-22dc-11eb-846c-4e58fbb4f7ea.png">

**Comment by JasonXuDeveloper** [comment]
bug 已修复，3分支都解决了，参考使用ConverDemo即可
