### ISSUE TITLE
移动端（Android）没实时阴影

### ISSUE THREAD

**Issue by goagor** [JasonXuDeveloper/JEngine#213]
版本：0.6.x
实时光照 移动端（Android）无阴影

框架工程和项目工程 设置一模一样

设置点：
1.Quality
2.灯光（平行光）
3.模型（系统自带 Cube Plane）

4.材质（系统自带）
5.场景（本地/热更）
6.不同机型（huawei / vivo / 1+ / redmi）

**Comment by JasonXuDeveloper** [comment]
Bundle Master下已解决
