### ISSUE TITLE
当在0.63的工程中使用Naninovel Visual Novel Engine的插件时候打包会报错

### ISSUE THREAD

**Issue by wukp88** [JasonXuDeveloper/JEngine#226]
同样的工程在0.5能正常打包，没有出现下面的报错提示

An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it.
UnityEditor.BuildPipeline:BuildAssetBundles (string,UnityEditor.AssetBundleBuild[],UnityEditor.BuildAssetBundleOptions,UnityEditor.BuildTarget)
libx.BuildScript:BuildAssetBundles () (at Assets/Dependencies/XAsset/Editor/BuildScript.cs:251)
JEngine.Editor.BuildBundles/<>c/<<BuildAssetBundles>b__0_0>d:MoveNext () (at Assets/Dependencies/JEngine/Editor/XAssetTools/BuildBundles.cs:46)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

**Comment by JasonXuDeveloper** [comment]
插件导入后报错，请提供TextMeshPro版本

**Comment by JasonXuDeveloper** [comment]
应该是有资源的依赖无限递归了导致的错误
