### ISSUE TITLE
手机热更新资源下载问题

### ISSUE THREAD

**Issue by zhangyuxing1980** [JasonXuDeveloper/JEngine#229]
手机热更新，下载更新资源过程中 将游戏进程切换到后台（20秒后），再切换回来无法恢复更新（不会下载资源），一直停在那。

检查代码怀疑是 Restart 方法逻辑有问题。其中的for 循环，如果是继续更新， _finishedIndex的数量是 已经完成的数量，而 max 还是 3， 那就会导致这个 for 循环基本都进不去。for (var i = _finishedIndex; i <  max; i++)

另外，就将代码改为： for (var i = _finishedIndex; i < _finishedIndex + max; i++)， 更新是可以恢复了，但是已更新的资源提示又是从 0开始。假设你总共要更新 600M ，而你在300M 的时候将游戏切换到后台，在切换回来，通过上面的修改后可以继续更新，但是显示已经的资源还是从 0 M 开始，这时继续更新，显示到了 300M后，就能进入游戏了。所以应该只是显示的问题。
查看代码发现GetDownloadSize 这个方法对于大文件来说，会不准确。

**Comment by jimmmmmmmmmyfunnnnnnny** [comment]
@JasonXuDeveloper  +1

**Comment by JasonXuDeveloper** [comment]
Bundle Master下已解决
