### ISSUE TITLE
构造不默认赋值

### ISSUE THREAD

**Issue by qn9663** [JasonXuDeveloper/JEngine#23]
IType type = Init.appdomain.LoadedTypes[classType];
            Type t = type.ReflectionType;//获取实际属性
            var instance = _class.UseConstructor
                ? Init.appdomain.Instantiate(classType)
                : new ILTypeInstance(type as ILType, false);

 : new ILTypeInstance(type as ILType, false); 这个构造出来的对象不会默认赋值. 但Instantiate没问题.
举例:
```class a :Jbehavior
{
   public List<string> list = new List<string>();

public a()
{
 debug.log(list.count)//null point
}
}
```

**Comment by JasonXuDeveloper** [comment]
是的，ILRuntime就是这样，所以classBind有useConstructor选项，使用ClassBind生成热更类，可以带构造函数
热更工程里，AddComponent也可以带构造函数来Add，在CLR方法重定向的Helper里改一下就好，我记得我改过了，我今天确认一下，如果没改我会提交一个AddComponent也带构造函数的修改

**Comment by JasonXuDeveloper** [comment]
本地生成热更类，建议ClassBind，或者了解ILRuntime的底层，ILRuntime生成热更类，带构造函数的生成只能Instantiate。

**Comment by JasonXuDeveloper** [comment]
检查了一下，热更工程AddComponent有构造值，本地工程用ClassBind也有构造值，自己写的话，只能Instantiate来带构造值，这个是ILRuntime的限制，当然也可以魔改ILRuntime底层，让new ILTypeInstance支持构造函数，但不建议自己改，需要一定水平

**Comment by JasonXuDeveloper** [comment]
截图是CLR方法重定向的截图，热更里，带构造函数来AddComponent了

<img width="1094" alt="iShot2020-11-10 14 25 32" src="https://user-images.githubusercontent.com/48086348/98623967-e4f49980-2360-11eb-8741-78b583878c8c.png">
