### ISSUE TITLE
JsonMapper.ToObject<List<JsonData>>会引发IndexOutOfRangeException

### ISSUE THREAD

**Issue by liuweichicun** [JasonXuDeveloper/JEngine#232]
我目前规避这个异常的方式：
JsonMapper 第 488 行更改为 ：                
` bool isIntKey = t_data.IsDictionary && value_type.GetGenericArguments().Length > 0 && value_type.GetGenericArguments()[0] == typeof(int);`
JsonMapper 第 586行更改为：
` var converter = dicTypes.Length > 0 ? System.ComponentModel.TypeDescriptor.GetConverter(dicTypes[0]) : null;`

**Comment by JasonXuDeveloper** [comment]
JsonData本就是IList, IOrderedDictionary，没必要用List<JsonData>，因此才会出问题

**Comment by JasonXuDeveloper** [comment]
用：LitJson.JsonMapper.ToObject
别用泛型方法获取JsonData
