### ISSUE TITLE
ClassBind在自动匹配全部Field时，多个Button会获取不到【具体数量没测试，我声明的是8个，2个btn可以，8个就匹配不到】

### ISSUE THREAD

**Issue by liuweichicun** [JasonXuDeveloper/JEngine#235]

**Comment by JasonXuDeveloper** [comment]
无法复现

![A0B170AF-D86C-48FF-A35E-67B5BBEB55AB](https://user-images.githubusercontent.com/48086348/147994421-292b15f5-ab16-4526-b175-673a36c3de24.png)
![A565EC7FF70AD2DB434EFDECC683E520](https://user-images.githubusercontent.com/48086348/147994427-4758d434-e5f6-46d0-9d47-29a0487fbfe3.jpg)
