### ISSUE TITLE
protocolBuf问题

### ISSUE THREAD

**Issue by YNightDream** [JasonXuDeveloper/JEngine#237]
引擎自带工具导出的c#文件都是getter,setter访问方式，导致安卓平台序列化的时候空对象，即使手动改变访问方式，会出现安卓序列化的结果是错误的无法完成通信，电脑结果全部一致可以通信

**Comment by JasonXuDeveloper** [comment]
提供一份问题代码，我好测试

**Comment by YNightDream** [comment]
之前搞错了我，验证了一下，{get; set;}安卓没法识别删除了就行序列化结果相同

**Comment by JasonXuDeveloper** [comment]
好，那就{get;set;}问题了，这个是ilrt的问题，暂时无法解决
