### ISSUE TITLE
生命周期顺序问题.

### ISSUE THREAD

**Issue by qn9663** [JasonXuDeveloper/JEngine#24]
研读代码发现生命周期顺序可能被改变:
```       
     if (_class.ActiveAfter)
            {
                if (_class.BoundData == false && _class.RequireBindFields)
                {
                    Log.PrintError($"自动绑定{this.name}出错：{classType}没有成功绑定数据，无法自动激活，请手动！");
                    return null;
                }

                clrInstance.enabled = true;<----这里
                clrInstance.Awake();
            }```

unity生命周期应该为:
如果addComponent前,gameobject.active == true时
Awake
OnEnable
OnStart
Update

如果addComponent前,gameobject.active == false时
什么也不做.

同时应该判断 
 if (_class.ActiveAfter && gameobject.active)
{
clrInstance.Awake();
 clrInstance.enabled = true;<---但未证实会不会多次调用.
}

**Comment by JasonXuDeveloper** [comment]
收到，会改JBehaviour，如果```gameObject.active==false```那就会等待到```true```，然后再进行```Init```

**Comment by qn9663** [comment]
加油,绑定这块我认为可以再改进一下.我刚刚尝试把他改成自动绑定.大概思路是对需要绑定的gameobject后面加上@符号,然后收集,根据自定义的优先级和名字前缀取到优先的组件.根据排除表去除不用收集的组件.用来收集到AssemblyQualifiedName也就是xx.GetType().AssemblyQualifiedName;最后通过Type t = Type.GetType(field.AssemblyQualifiedName);数组和变量我项目里基本没有,所以不处理.
                        //判断变量的值是在热层还是引擎层
                        if (isHotScript)
                        {
                            string tName = varField.FieldType.Name;
                            var classBind = targetGo.GetComponent<ClassBind>(); //变量指向了HotLayer中的类时,对其进行初始化

                            if (classBind)
                            {
                                classBind.Bind();
                                varField.SetValue(ilInstance, classBind.mIlInstance);
                            }

                            _class.BoundData = true;
                        }
                        else
                        {
                            //将Unity对象赋值给热层的脚本变量
                            Type t = Type.GetType(field.AssemblyQualifiedName);
                            if (t == null)
                            {
                                Debug.LogError($"gameobject : {field.gameObject} 无法找到 {hTypeFullName}变量名为:{field.fieldName}的dll路径为空");
                                continue;
                            }

                            Component component = targetGo.GetComponent(t);
                            _class.BoundData = true;
                            varField.SetValue(ilInstance, component);
                        }
                    }

**Comment by JasonXuDeveloper** [comment]
自动绑定的话，绑定组件没什么问题吧，对UnityComponent进行赋值，有判断类型在哪里的操作
<img width="845" alt="iShot2020-11-10 17 34 26" src="https://user-images.githubusercontent.com/48086348/98636449-fcd91700-237a-11eb-829b-514648d8b88f.png">

**Comment by JasonXuDeveloper** [comment]
JBehaviour生命周期的地方已经修复，等提交
<img width="479" alt="iShot2020-11-10 17 37 31" src="https://user-images.githubusercontent.com/48086348/98636670-707b2400-237b-11eb-85a2-9fa0dde5c5ff.png">
ClassBind这块，没什么问题，会判断热更类和本地类
