### ISSUE TITLE
websocket在ios上断网了不会走OnDisconnect和OnError 甚至 OnClose都不会走到。

### ISSUE THREAD

**Issue by jimmmmmmmmmyfunnnnnnny** [JasonXuDeveloper/JEngine#241]
测试ios websocket断网响应很慢，也不会走断开的和连接失败的回调里。安卓和win32没有发现这个问题

**Comment by JasonXuDeveloper** [comment]
请提供代码

**Comment by jimmmmmmmmmyfunnnnnnny** [comment]
就是JEngine打包ios测试下websocket就有。。

**Comment by JasonXuDeveloper** [comment]
提供代码啊，demo里也没有websocket相关的代码啊

**Comment by jimmmmmmmmmyfunnnnnnny** [comment]
会没有呢？就是这个的呀。。
![image](https://user-images.githubusercontent.com/26768352/147387183-6d838d0d-bc1e-49b0-8568-ff05f0487c42.png)

**Comment by JasonXuDeveloper** [comment]
提供你的使用案例啊。。。。。。不然我咋复现
我这里有2种连接方式我也不知道你用的是哪个啊

**Comment by jimmmmmmmmmyfunnnnnnny** [comment]
webscoket 的那个版本 然后设备是iOS15的系统就会出现这个问题。。。

**Comment by JasonXuDeveloper** [comment]
测试了一下，没有复现问题，没及时检测到断开连接可能是网络波动问题
