### ISSUE TITLE
FindObjectOfType导致崩溃的问题

### ISSUE THREAD

**Issue by miuleung** [JasonXuDeveloper/JEngine#242]
GameObject.FindObjectOfType<T>();
GameObject.FindObjectOfType(typeof(**));
这两接口都会导致整个unity崩溃。

PS：Enum.IsDefined接口也无法使用（但不会导致崩溃）

**Comment by JasonXuDeveloper** [comment]
用泛型方法

**Comment by JasonXuDeveloper** [comment]
`Object.FindObjectsOfType<T> `

**Comment by miuleung** [comment]
> 用泛型方法

请问第二个问题呢
Enum.IsDefined接口也无法使用

**Comment by JasonXuDeveloper** [comment]
> > 用泛型方法
> 
> 
> 
> 请问第二个问题呢
> 
> Enum.IsDefined接口也无法使用

这个得看ilrt支不支持，得去问问，这个我不记得了

**Comment by miuleung** [comment]
> 

thanks
