### ISSUE TITLE
FindObjectOfType使用泛型获取到的类型不可预测

### ISSUE THREAD

**Issue by miuleung** [JasonXuDeveloper/JEngine#243]
FindObjectOfType通过泛型确实是可以使用了，但找到的类型与目标类型不一样，有时候可以找到对应的类型，有时候找到却不一样。

**Comment by miuleung** [comment]
例如：
我在JUIExample中Start方法下添加逻辑：
` var obj1 = Object.FindObjectOfType<AutoBindDemo2>();
var obj2 = Object.FindObjectOfType<InstantiateDemo>();
Debug.LogError($" {obj1} {obj2} {Object.FindObjectsOfType<InstantiateDemo>().Length}");`

得到的log却是：

`JEngine.UI.JUI JEngine.UI.JUI 1`

**Comment by miuleung** [comment]
例如：
我在JUIExample中Start方法下添加逻辑：
` var obj1 = Object.FindObjectOfType<AutoBindDemo2>();
var obj2 = Object.FindObjectOfType<InstantiateDemo>();
Debug.LogError($" {obj1} {obj2} {Object.FindObjectsOfType<InstantiateDemo>().Length}");`

得到的log却是：

`JEngine.UI.JUI JEngine.UI.JUI 1`

**Comment by JasonXuDeveloper** [comment]
FindObjectOfType没做重定向，只有FindObjectsOfType做了，我今天补一个

**Comment by JasonXuDeveloper** [comment]
已修复，等0.7发布

**Comment by miuleung** [comment]
> FindObjectOfType没做重定向，只有FindObjectsOfType做了，我今天补一个

看了一下代码实现，Tools.FindObjectsOfTypeAll中逻辑为只找当前场景中的类型，我猜类型DontDestroyOnLoad后就没办法找到了。
而我尝试了一下，确实如此。请问有办法吗？

**Comment by JasonXuDeveloper** [comment]
> > FindObjectOfType没做重定向，只有FindObjectsOfType做了，我今天补一个
> 
> 看了一下代码实现，Tools.FindObjectsOfTypeAll中逻辑为只找当前场景中的类型，我猜类型DontDestroyOnLoad后就没办法找到了。 而我尝试了一下，确实如此。请问有办法吗？

这个没有办法解决了😂，我记得Unity自己的FindObjectsOfType也不一定能找到DontDestoryOnLoad的东西吧

**Comment by miuleung** [comment]
> > > FindObjectOfType没做重定向，只有FindObjectsOfType做了，我今天补一个
> > 
> > 
> > 看了一下代码实现，Tools.FindObjectsOfTypeAll中逻辑为只找当前场景中的类型，我猜类型DontDestroyOnLoad后就没办法找到了。 而我尝试了一下，确实如此。请问有办法吗？
> 
> 这个没有办法解决了😂，我记得Unity自己的FindObjectsOfType也不一定能找到DontDestoryOnLoad的东西吧

可惜了。
但Unity自己的FindObjectsOfType是可以找到的。利用这个特性能保证挂载的Mono单例为全局唯一，即使场景反复来回切换，也能使单例不会重复生成。

**Comment by JasonXuDeveloper** [comment]
> > > > FindObjectOfType没做重定向，只有FindObjectsOfType做了，我今天补一个
> > > 
> > > 
> > > 看了一下代码实现，Tools.FindObjectsOfTypeAll中逻辑为只找当前场景中的类型，我猜类型DontDestroyOnLoad后就没办法找到了。 而我尝试了一下，确实如此。请问有办法吗？
> > 
> > 
> > 这个没有办法解决了😂，我记得Unity自己的FindObjectsOfType也不一定能找到DontDestoryOnLoad的东西吧
> 
> 可惜了。 但Unity自己的FindObjectsOfType是可以找到的。利用这个特性能保证挂载的Mono单例为全局唯一，即使场景反复来回切换，也能使单例不会重复生成。

似乎可以支持

**Comment by JasonXuDeveloper** [comment]
重定向FindObjectsOfType的本质：
```c#
 if (type is ILRuntimeType ilType)
            {
                var adapters = Tools.FindObjectsOfTypeAll<CrossBindingAdaptorType>();
                var ilInstances = ((ILTypeInstance[]) Tools.GetHotComponent(adapters, ilType.ILType))
                    .Select(i => i.CLRInstance).ToArray();
                int n = ilInstances.Length;
                res = Array.CreateInstance(ilType.ILType.TypeForCLR, n);
                for (int i = 0; i < n; i++)
                    ((Array) res).SetValue(ilInstances[i], i);
            }
```
其实可以把```Tools.FindObjectsOfTypeAll<CrossBindingAdaptorType>();```改成Unity的FindObjectsOfType，我等下试试

**Comment by JasonXuDeveloper** [comment]
可以实现，就是性能会略微下降，我等下改一下

**Comment by miuleung** [comment]
> 

666

**Comment by JasonXuDeveloper** [comment]
已经在dev分支提交了
