### ISSUE TITLE
从stream 复制资源后，第一次增量，第二次全量，在这之后又是增量了

### ISSUE THREAD

**Issue by fatpander** [JasonXuDeveloper/JEngine#244]
IOS打包时，热更不走增量热更，IOS代码不使用vfs，导致IOS打包一直是全量热更，严重消耗流量。XAsset的问题。

**Comment by JasonXuDeveloper** [comment]
不用vfs也不是全量啊

**Comment by JasonXuDeveloper** [comment]
不管用不用vfs，后续热更都是通过manifest对比差异文件，然后下载有差异的ab进行更新，目前的配置里，UI文件夹是打为一个AB的，也就是说你改一张图，就需要重新下载整个UI文件夹大小的AB，但这个还是差异增量更新的

**Comment by fatpander** [comment]
我们游戏将热更包移动到streaming assets中，第一次进游戏的时候是增量更新的，但退出重进后几乎更新了全部资源，在这之后的热更都是正常的

**Comment by JasonXuDeveloper** [comment]
就是从stream 复制资源后，第一次增量，第二次全量，在这之后又是增量了是吗

**Comment by fatpander** [comment]
是的

**Comment by fatpander** [comment]
目前在mac上，非development模式在热更后也是无法运行的

**Comment by JasonXuDeveloper** [comment]
收到，我猜测是因为stream下的资源增量更新后在和服务端判断差异后被标记为全部都需要更新了，所以会导致一次全量下载

**Comment by JasonXuDeveloper** [comment]
editor能复现吗，能的话我直接editor测了

**Comment by JasonXuDeveloper** [comment]
> 目前在mac上，非development模式在热更后也是无法运行的

这个是平台不一样或密码不一样或hash冲突，估计需要清除缓存重新下载，然后才能好

**Comment by fatpander** [comment]
editor可以复现

**Comment by JasonXuDeveloper** [comment]
> editor可以复现

收到

**Comment by JasonXuDeveloper** [comment]
Bundle Master下已解决
