### ISSUE TITLE
关于场景加载时间长的问题

### ISSUE THREAD

**Issue by miuleung** [JasonXuDeveloper/JEngine#252]
前置提要：
1：一共两个场景，均添加进了热更逻辑中进行更新
2：在场景中会在两个场景之间来回切换

目前的问题是，切换场景花费时间非常长。测试过用正常项目原始API只需要3秒钟的时间，使用热更加载却需要接近两分钟

**Comment by JasonXuDeveloper** [comment]
加载时间长这个似乎没办法，因为用的unity底层的加载ab包内场景的api，慢和快都没办法优化了😂

**Comment by miuleung** [comment]
> 加载时间长这个似乎没办法，因为用的unity底层的加载ab包内场景的api，慢和快都没办法优化了😂

但这差距也太大了吧😂

**Comment by JasonXuDeveloper** [comment]
最好拉master搞一个复现测试，写个log看看加载了多久，附带个截图，然后测试的工程的Asset目录压缩个zip发我看看

**Comment by miuleung** [comment]
> 最好拉master搞一个复现测试，写个log看看加载了多久，附带个截图，然后测试的工程的Asset目录压缩个zip发我看看

我准备下。

另外我发现一个问题：
在热更项目中使用unity原生API（SceneManager.LoadSceneAsync），第一次加载某个场景时会很快（几秒钟，与正常项目加载速度相同，但不会有被热更），一旦重复加载后（即第二次以后），时间就会变成接近两分钟

**Comment by JasonXuDeveloper** [comment]
加载热更场景用AssetMgr.LoadSceneAsync

**Comment by miuleung** [comment]
> 加载热更场景用AssetMgr.LoadSceneAsync

两种都试过。我最前面说的慢就是用的这个api加载的。
而用unity原生API加载第一次虽然快，但并没从AB包中加载，第二次之后却会从AB包中加载场景，这其中逻辑没弄明白

**Comment by JasonXuDeveloper** [comment]
行，你搞个可以复现的项目，压缩成zip上传上来我去看看

**Comment by JasonXuDeveloper** [comment]
Bundle Master下已解决

**Comment by miuleung** [comment]
> Bundle Master下已解决

所以还真是旧版XAsset问题?

**Comment by JasonXuDeveloper** [comment]
是的，他的封装可能有点问题，现在用Bundle Master加载场景后用unity的SceneManager即可，也可以用AssetMgr的封装
