### ISSUE TITLE
求解：Android端调用Unity函数失败问题

### ISSUE THREAD

**Issue by jijiale520** [JasonXuDeveloper/JEngine#256]
我在场景中添加了不会被销毁的物体Manages，然后将ClassBind脚本挂在这个物体上，再将自己写的AndroidHelper脚本信息添加Scripts To Bind里，最后发现我在AndroidStudio里调用AndroidHelper的BackPressed()方法时提示我
*SendMessage: object **Manages** does not have receiver for function **BackPressed**!*
正常调是没问题的

**Comment by JasonXuDeveloper** [comment]
SendMessage是安卓的SendMessage吗？还是Unity的？目前只支持热更工程下调用Unity的SendMessage来执行热更的函数，不支持安卓层的SendMessage执行热更层的函数

**Comment by JasonXuDeveloper** [comment]
得自己在主工程写个桥接工具，让安卓层SendMessage到主工程的桥接工具，然后桥接工具去获取ClassBind创建的那个对象，然后Invoke其对应方法，例如：
```c#
//主工程 
public class AndroidSendMessageBridge: MonoBehaviour{
public class SendMessageToHotUpdate(string hottypename){
string hotMethod = "hotMethod";
List<CrossBindingAdaptorType> adapters = Tools.GetAllMonoAdapters();
ILTypeInstance instance = Tools.GetHotComponent(adapters,InitJEngine.Appdomain.GetType(hottypename));
InitJEngine.Appdomain.Invoke(hottypename, hotMethod, instance, Tools.Param0);//Param0可以换成参数
}
}
```
```c#
//热更层
public class Test:MonoBehaviour{
public void ReceiveMsg(){
Debug.Log("收到了Android层的SendMessage");
}
}
```
java层SendMessage到AndroidSendMessageBridge的SendMessageToHotUpdate，参数传ReceiveMsg即可
