### ISSUE TITLE
UnityEngine.EventSystems中IDragHandler无法被激活

### ISSUE THREAD

**Issue by kangming06** [JasonXuDeveloper/JEngine#281]
如果在不热更代码中OnDrag可以正常使用，但只要放在热更工程就无法被激活
![image](https://user-images.githubusercontent.com/74850890/160241261-5fd6e272-4903-47bc-874c-d20831d046d8.png)

**Comment by liuweichicun** [comment]
热更工程不可以使用多继承，这是ILRuntime的限制。如果要实现你你想要的效果，可以尝试下面两种方法：

1.  在主工程封装一个父类，实现你想要的接口，然后在热更工程继承这个父类（单继承）。
2.  在主工程发布事件，在热更工程订阅。
