### ISSUE TITLE
编辑器真机模式下正常运行真机功能缺失

### ISSUE THREAD

**Issue by kangming06** [JasonXuDeveloper/JEngine#293]
由于在热更工程中Rigidbody类缺失，所以添加了UnityEngine.PhysicsModule.dll的引用
引用添加后编辑器所有模式均可以运行，也可以使用Rigidbody
但是把包打出来以后真机上无法使用rigidbody其他功能均正常。
测试代码:

using System;
using UnityEngine;

namespace HotUpdateScripts
{
    public class Player:MonoBehaviour
    {
        private Rigidbody rigid;

        void Awake()
        {
            rigid = GetComponent<Rigidbody>();
            
        }

        private void Update()
        {
            rigid.AddForce(new Vector3(1f,0f,1f));
        }
    }
}

**Comment by JasonXuDeveloper** [comment]
被裁剪了，做clr绑定再出包

**Comment by kangming06** [comment]
已经进行clr绑定但依然无法使用rigidbody

**Comment by JasonXuDeveloper** [comment]
需要看logcat上的报错，刚体经过测试是可以正常使用的

**Comment by kangming06** [comment]
已确认是因为手机刷新频率低导致现象不明显

**Comment by JasonXuDeveloper** [comment]
收到
