### ISSUE TITLE
JBehaviour 建议可以控制关闭Loop的生命周期

### ISSUE THREAD

**Issue by xxsstc** [JasonXuDeveloper/JEngine#302]
当场景挂太多JBehaviour 的时候

**Comment by miuleung** [comment]
说起这个，JBehaviour 与MonoBehaviour 相比有个很奇特的设定：

**Comment by JasonXuDeveloper** [comment]
> 说起这个，JBehaviour 与MonoBehaviour 相比有个很奇特的设定：
> Loop函数在其挂载物体被隐藏时仍然会一直在执行，新旧版本均是如此，跟MonoBehaviour 的使用习惯相背

了解，这块应该优化一下
