### ISSUE TITLE
编辑器运行prefix为空的问题

### ISSUE THREAD

**Issue by miuleung** [JasonXuDeveloper/JEngine#308]
问题描述：
目前为了避免冲突，PlayerPrefs的数据使用的是JEngine.lock中的UID进行区分。但在运行时，一些逻辑获取PlayerPrefs数据是在SetPrefix执行之前，这就导致了此时Setting._prefix是空的，PlayerPrefs获取的均是默认值。

例如：
1：改变默认启动场景Init为场景A，保存。
2：Build Settings中同步修改场景
3：编辑器运行，此时因为ChangeScene.DoChange运行是在SetData.Update之前，所以Setting.StartUpScenePath获取的永远为默认值Init场景，会直接把当前运行场景A强制修改为Init

**Comment by JasonXuDeveloper** [comment]
收到，干脆直接改这一块吧，全写入lock文件或者用editorPrefs，这块我会想想怎么解决的
