### ISSUE TITLE
打包64位安卓包，闪退。

### ISSUE THREAD

**Issue by jiangjialiv** [JasonXuDeveloper/JEngine#310]
打包64位安卓包，闪退。

**Comment by JasonXuDeveloper** [comment]
请提供详细信息

**Comment by JasonXuDeveloper** [comment]
我这边测试的时候没问题的，是不是有什么插件在64位环境会导致闪退？

**Comment by jiangjialiv** [comment]
> 我这边测试的时候没问题的，是不是有什么插件在64位环境会导致闪退？

我这边再测试一下。

**Comment by jiangjialiv** [comment]
打包安卓64位，在蓝叠模拟器上运行时闪退。
APP包，链接地址：
链接: https://pan.baidu.com/s/1r327JGWF66LKNxwv-CeHow 提取码: kdpn

**Comment by JasonXuDeveloper** [comment]
能否直接提供闪退堆栈，以及闪退时候的操作

**Comment by jiangjialiv** [comment]
> 

点击图标运行就直接退出了。还找不到这些Log文件。我也在想办法。

**Comment by JasonXuDeveloper** [comment]
用logcat连上模拟器，adb也可以，然后运行游戏，看看是什么导致闪退的。之前我有个sdk插入了一个activity导致进游戏就闪退，你可能也遇到了类似问题。

**Comment by jiangjialiv** [comment]
> 

好呢。我试试。

**Comment by jiangjialiv** [comment]
Fatal signal 4 (SIGILL), code 0, fault addr 0x2752000019f6 in tid 6646 (com.jiangjiali.)

**Comment by jiangjialiv** [comment]
![image](https://user-images.githubusercontent.com/94029615/164225826-f1fe8c00-2f5b-43f3-a06e-337eebee5c81.png)
这个是不是你说的那个 activity

**Comment by JasonXuDeveloper** [comment]
这个是游戏线程挂了

**Comment by JasonXuDeveloper** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/48086348/164226621-a8372474-9568-4ed2-9c5d-be5f5889e891.png">
应该是插件问题，和框架应该没啥关系

**Comment by jiangjialiv** [comment]
> 

好呢。我查一下。

**Comment by jiangjialiv** [comment]
我使用的 i2CPP编译。游戏运行时会有一些意想不到的问题。

**Comment by jiangjialiv** [comment]
使用mono编译，游戏就完全正常。
是因为ILRuntime只只支持mono的原因吗？

**Comment by JasonXuDeveloper** [comment]
ilrt就是针对il2cpp设计的...

**Comment by JasonXuDeveloper** [comment]
你得检查一下报错了，估计是某些报错导致的问题，应该和框架无关
