### ISSUE TITLE
How to build the `HotUpdateScripts.csproj` solution on MacOS with VSCode?

### ISSUE THREAD

**Issue by zhoujinfu** [JasonXuDeveloper/JEngine#338]
It seem that the baseline HEAD built with some errors when CLI command `dotnet build` .

**Comment by zhoujinfu** [comment]
Envs:
OS: MacOS 12.0.1
dotnet sdk: 6.0+

**Comment by JasonXuDeveloper** [comment]
please provide error detail

**Comment by zhoujinfu** [comment]
sry, I just followed the [create-and-publish-a-package-using-the-dotnet-cli](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli) to rebuild the HotUpdateScripts using dotnet CLI `dotnet  build`. It seem that the `HotUpdateScripts.csproj` isn't a standard classlib.

`dotnet build` using ESBuild internally as quote below from  https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#msbuild:
> Running dotnet build is equivalent to running dotnet msbuild -restore; however, the default verbosity of the output is different.

errors snapshot:

![image](https://user-images.githubusercontent.com/15223662/172158036-afd83080-530c-4100-97e7-04dde2dee2c1.png)

**Comment by JasonXuDeveloper** [comment]
change configuration of the csproj, set the platform to "anycpu" for macOS, as there can not be space in configuration. However, on windows, it should be "Any CPU"
