### ISSUE TITLE
调用获取分包版本号时会出现 Sharing violation on path 报错

### ISSUE THREAD

**Issue by k1104480005** [JasonXuDeveloper/JEngine#343]
![4QU~YC%S2OGTI)`BZBHSV(L](https://user-images.githubusercontent.com/30077226/174799303-9cbd163f-1086-44a5-840b-419c5a28acea.jpg)
在热更工程调用 Updater.CheckPackage 、 Updater.GetLocalPackageVersion、Updater.GetRemotePackageVersion 后会出现这样的报错，暂时不清楚是不是我姿势不对，正在调查

![image](https://user-images.githubusercontent.com/30077226/174815793-68cb7e71-f116-4309-8762-a16dbd46cbd4.png)
我找到原因了，是因为更新分包结束后（即回调进度为1f时），我立刻查询了分包的版本号所以出现这个报错。我的做法是在Updater.cs更新结束 这里等一下再回调就没问题了~

**Comment by JasonXuDeveloper** [comment]
要一步步来
参考Updater.UpdatePackage接口的内部实现，建议直接用这个
