### ISSUE TITLE
热更脚本生命周期方法执行顺序不对

### ISSUE THREAD

**Issue by Naruto778520** [JasonXuDeveloper/JEngine#349]
![image](https://user-images.githubusercontent.com/17754056/175919199-4001f9c6-8004-446a-8034-ded90070212b.png)
![`7LBKO18T5J R8NB BRJRG](https://user-images.githubusercontent.com/17754056/175919293-ad4aae17-6d29-4956-b6c7-b54defb85ad7.png)
我在Unity中将Fixed Timestep的时间设置为1秒, 这个间隔时间远远大于在正常情况下的Update方法的调用间隔, 所以Update应该先于FixedUpdate被调用, 但是测试后, 发现FixedUpdate在第一次时确先于Update被调用.

在Unity工程中, 当生命周期开始时, 是先调用完一个脚本的Awake, OnEnable方法, 再调用别一个脚本的Awake, OnEnable方法, 但是热更脚本的生命周期是先调用完所有脚本的Awake方法, 再调用所有脚本的Onable方法.

**Comment by JasonXuDeveloper** [comment]
同时调用所有的Awake，OnEnable，是JEngine特意针对MonoBehaviour做的性能优化
