### ISSUE TITLE
SceneManager.LoadScene("Init"); from HotUpdateScripts

### ISSUE THREAD

**Issue by theninh** [JasonXuDeveloper/JEngine#355]
Hi Jason, Have a nice day!

I have a question: i want to reload scene Init from HotUpdateScripts, is it possible?

i reveced error
cationException: Exception has been thrown by the target of an invocation.
object System.Reflection.MonoMethod.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
object System.Reflection.MethodBase.Invoke(object obj, object[] parameters)
object ILRuntime.CLR.Method.CLRMethod.Invoke(ILIntepreter intepreter, StackObject* esp, List<object> mStack, bool isNewObj) in Assets/Dependencies/ILRuntime/ILRuntime/CLR/Method/CLRMethod.cs:line 346
StackObject* ILRuntime.Runtime.Intepreter.ILIntepreter.ExecuteR(ILMethod method, StackObject* esp, out bool unhandledException) in Assets/Dependencies/ILRuntime/ILRuntime/Runtime/Intepreter/RegisterVM/ILIntepreter.Register.cs:line 2949
Rethrow as ILRuntimeException: Exception has been thrown by the target of an invocation.
IL_001e: callvirt !1 System.Collections.Generic.Dictionary`2<UnityEngine.GameObject,System.Collections.Generic.HashSet`1<JEngine.Core.JBehaviour>>::get_Item(!0)(JIT_0007:callvirt r2, r3, r1, 148)
JEngine.Core.JBehaviour.GameObjectDictCheckNullJBehaviour() (at HotUpdateScripts/JEngine/Core/JBehaviour.cs:701)
JEngine.Core.JBehaviour/JBehaviourMgr.Update() (at HotUpdateScripts/JEngine/Core/JBehaviour.cs:107)
IL_001e: callvirt !1 System.Collections.Generic.Dictionary`2<UnityEngine.GameObject,System.Collections.Generic.HashSet`1<JEngine.Core.JBehaviour>>::get_Item(!0)(JIT_0007:callvirt r2, r3, r1, 148)
JEngine.Core.JBehaviour.GameObjectDictCheckNullJBehaviour() (at HotUpdateScripts/JEngine/Core/JBehaviour.cs:701)
JEngine.Core.JBehaviour/JBehaviourMgr.Update() (at HotUpdateScripts/JEngine/Core/JBehaviour.cs:107)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
JEngine.Core.Logger:LogException(Exception, Object) (at Assets/Dependencies/JEngine/Core/Logger/LogHandler.cs:201)
JEngine.Core.Logger:LogException(Exception, Object) (at Assets/Dependencies/JEngine/Core/Logger/LogHandler.cs:201)
UnityEngine.Debug:LogException(Exception)
JEngine.Core.LifeCycleMgr:ExecuteItems(HashSet`1, Boolean, Func`2) (at Assets/Dependencies/JEngine/Core/Manager/LifeCycleMgr.cs:225)
JEngine.Core.LifeCycleMgr:Update() (at Assets/Dependencies/JEngine/Core/Manager/LifeCycleMgr.cs:303)

**Comment by JasonXuDeveloper** [comment]
It is possible, however you have to destroy (literally) everything you have created before you reload from scene init.
You gotta unload ```InitJEngine.AppDomain```, in the meantime, you need to manually destroy everything that relates to a hot update script in your DONTDESTORYONLOAD session, i.e. JBehaviourMgr is one of them, that's why there is an exception.

**Comment by theninh** [comment]
Thanks for reply, Can you integrate reload scene init feature in JEngine? I think it's a great feature, users can play the game without waiting for the update scene to load, the update notification will be displayed at the discretion of the developer.
Thanks so much

**Comment by JasonXuDeveloper** [comment]
> Thanks for reply, Can you integrate reload scene init feature in JEngine? I think it's a great feature, users can play the game without waiting for the update scene to load, the update notification will be displayed at the discretion of the developer.
> Thanks so much

Currently this feature is implemented in another JEngine version (a Chinese version). However, as recently I will reconstruct some JEngine's low level code to support loading multiple assemblies (probably will come out in v0.7.4), there is a great chance such that I will include hot reload feature in that version.
Accordingly, ILRuntime's author claims that he might implement the actual hot reload feature (which means I can use it to reload method info pointers in play time, and no need to jump back to init scene and restart your game). This indicates I might also wait until ILRuntime's author implements that feature, so then I will be able to implement a better hot reload strategy feature in JEngine.
So we will see, this feature might come in soon.

**Comment by theninh** [comment]
Good news, thanks so much 👯
