### ISSUE TITLE
enum : byte 序列化报错

### ISSUE THREAD

**Issue by TZSG** [JasonXuDeveloper/JEngine#388]
enum : byte时，StringifyHelper.JSONSerliaze序列化报错

**Comment by JasonXuDeveloper** [comment]
master下无问题，请检查是不是改过项目的LitJson
<img width="770" alt="image" src="https://user-images.githubusercontent.com/48086348/187072070-39840da0-bcd2-4558-a826-9864dce63228.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/48086348/187072075-993b87d8-7c34-4e5b-a541-195af045e0c9.png">
