### ISSUE TITLE
float 序列化报错

### ISSUE THREAD

**Issue by TZSG** [JasonXuDeveloper/JEngine#389]
[Serializable]
public class Test
{
    public float test;
    public Test()
    {
        test = 0;
    }
}

Test testB = new Test();
StringifyHelper.JSONSerliaze(testB);

JsonException: Max allowed object depth reached while trying to export from type System.Single
LitJson.JsonMapper.WriteValue (System.Object obj, LitJson.JsonWriter writer, System.Boolean writer_is_private, System.Int32 depth) (at Assets/Dependencies/LitJson/JsonMapper.cs:1008)
LitJson.JsonMapper.WriteValue (System.Object obj, LitJson.JsonWriter writer, System.Boolean writer_is_private, System.Int32 depth) (at Assets/Dependencies/LitJson/JsonMapper.cs:994)
LitJson.JsonMapper.WriteValue (System.Object obj, LitJson.JsonWriter writer, System.Boolean writer_is_private, System.Int32 depth) (at Assets/Dependencies/LitJson/JsonMapper.cs:994)

**Comment by JasonXuDeveloper** [comment]
在master的热更工程测试无问题，请检查有没有进入热更工程，并且有注册LitJsonHelper(```UnityProject/Assets/Scripts/Helpers/RegisterLitJsonHelper.cs```)
<img width="717" alt="image" src="https://user-images.githubusercontent.com/48086348/187071944-44537181-d3ee-4230-b67b-d14c24a80c46.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/48086348/187071950-251f8eb6-daec-47ce-b92e-19ef83322bb2.png">
