### ISSUE TITLE
下载完资源后，再进游戏报错。

### ISSUE THREAD

**Issue by jiangjiali** [JasonXuDeveloper/JEngine#408]
The AssetBundle 'Memory' can't be loaded because another AssetBundle with the same files is already loaded.
UnityEngine.AssetBundle:LoadFromMemory(Byte[])
BM.LoadBase:LoadAssetBundle(String) (at Assets/Dependencies/BundleMaster/BundleMasterRuntime/Base/LoadBaseRuntimeLoad.cs:95)
BM.LoadHandler:Load() (at Assets/Dependencies/BundleMaster/BundleMasterRuntime/LoadHandler.cs:134)
BM.AssetComponent:Load(LoadHandler&, String, Boolean, String) (at Assets/Dependencies/BundleMaster/BundleMasterRuntime/AssetComponent.cs:92)
BM.AssetComponent:Load(LoadHandler&, String, String) (at Assets/Dependencies/BundleMaster/BundleMasterRuntime/AssetComponent.cs:98)
JEngine.Core.AssetMgr:Load(String, String, Type) (at Assets/Dependencies/JEngine/Core/Manager/AssetMgr.cs:58)
JEngine.Core.AssetMgr:Load(String, String) (at Assets/Dependencies/JEngine/Core/Manager/AssetMgr.cs:45)
System.Reflection.MethodBase:Invoke(Object, Object[])

**Comment by JasonXuDeveloper** [comment]
这个是Updater填的MainPackageKey与Bundle配置文件配置的密码不一样导致的（或者没有开Bundle加密），参考文档打包资源部分即可

**Comment by jiangjiali** [comment]
好的。我检查一下。

**Comment by JasonXuDeveloper** [comment]
这个issue先关了，如果问题没解决可以再open，或者加qq群讨论下
