### ISSUE TITLE
卸载热更场景列表失败。

### ISSUE THREAD

**Issue by donitry** [JasonXuDeveloper/JEngine#438]
在当前场景下用JEngine设置里的热更场景列表中卸载场景失败.
unity 版本 2021.3.5
错误内容：

>Unloading the last loaded scene Assets/HotUpdateResources/Scene/Test.unity(build index: 3), is not supported. Please use SceneManager.LoadScene()/EditorSceneManager.OpenScene() to switch to another scene.

**Comment by JasonXuDeveloper** [comment]
测试了一下，卸载场景只可以卸载已加载的场景

<img width="967" alt="image" src="https://user-images.githubusercontent.com/48086348/204990360-a81eade9-5348-4ffa-b92a-b01c8306e9c6.png">

例如我加载了test和game，我就可以卸载test或game，但是至少得有一个场景存在，也就意味着我如果同时加载了2个场景，卸载其中任意一个后就无法继续卸载了

同时，直接打开的场景是无法卸载的，因为同时打开的场景只能有1个，不满足卸载条件
