### ISSUE TITLE
Do you support webgl?

### ISSUE THREAD

**Issue by theninh** [JasonXuDeveloper/JEngine#439]
When i build example in webgl, i got the error

[Error] Scene 'Assets/HotUpdateResources/Scene/Game.unity' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings...

[Error] ArgumentNullException: Value cannot be null.
Parameter name: _unity_self
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0

**Comment by JasonXuDeveloper** [comment]
webgl will be supported in the future version, hopefully first quarter of next year.
