### ISSUE TITLE
使用Instantiate接口复制嵌套的gameObject问题

### ISSUE THREAD

**Issue by duanma** [JasonXuDeveloper/JEngine#44]
比如 a是父节点，b是子节点
1.如果a上没有使用classbind,b使用了classbind，复制后会报错，数组越界，即clrInstances和clrInstances4Ins的数组长度不一致（注意：如果这里复制的不是.prefab，而是场景上的gameObject对象，测试发现复制.prefab没有问题）
2.复制后生命周期问题Awake和OnEnable和Start方法调用的次数问题，这个和复制非嵌套的gameObject一样

**Comment by JasonXuDeveloper** [comment]
已修复
