### ISSUE TITLE
Cross bind adapter生成错误

### ISSUE THREAD

**Issue by tpxxn** [JasonXuDeveloper/JEngine#449]
生成了基类里的UNITY_EDITOR的protected的方法

**Comment by tpxxn** [comment]
例如BaseMeshEffect 的基类 UIBehaviour 的 OnValidate和Reset方法

**Comment by JasonXuDeveloper** [comment]
研究了一下，这个办法无解，因为没办法用代码手段判断是否特定函数打了宏，所以这个只能手动删生成出来的多余的函数
