### ISSUE TITLE
最新Nino解析负数错误

### ISSUE THREAD

**Issue by L-Fone** [JasonXuDeveloper/JEngine#453]
![QQ截图20230107170356](https://user-images.githubusercontent.com/23207097/211143557-4a15a135-78f6-45d6-b213-aaa2afa11e9e.png)
![QQ截图20230107172232](https://user-images.githubusercontent.com/23207097/211143559-6e93f885-3dfb-420a-8802-106d1b40d20c.png)
![QQ截图20230107172401](https://user-images.githubusercontent.com/23207097/211143590-09d88340-94d4-4ca1-b49d-8e95e8e9dfbe.png)
如图所示，-136被解析成65400。Nino文件导出版本为图3。读取版本为当前最新master分支。

**Comment by JasonXuDeveloper** [comment]
导出时，x的类型是Float吗？

**Comment by L-Fone** [comment]
导出时，x的类型是Int型




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JasonXuDeveloper/JEngine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月7日(星期六) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JasonXuDeveloper/JEngine] 最新Nino解析负数错误 (Issue #453)





 
导出时，x的类型是Float吗？
