### ISSUE TITLE
gameObject.CreateJBehaviour<>();会报错

### ISSUE THREAD

**Issue by Yeeeeer** [JasonXuDeveloper/JEngine#455]
不知道为什么写法正常，但就是会报InvalidCastException: Specified cast is not valid.
新建一个工程导入Jengine也能正常CreateJBehaviour<>()
唯独附件这个工程会报错，

但把热更场景Test中的ManagerGame的ClassBind的active after取消勾选，就能正常
其中热更脚本ManagerGame里面啥也没写啊，太奇怪了

[JEngineTest_unity2021_3_12f1.zip](https://github.com/JasonXuDeveloper/JEngine/files/10391370/JEngineTest_unity2021_3_12f1.zip)

**Comment by JasonXuDeveloper** [comment]
可能是ILRuntime的bug，这部分代码于v0.8.0改了个方式，等0.8发布就行
