### ISSUE TITLE
je大概什么时候可以支持webgl呢

### ISSUE THREAD

**Issue by whl160118** [JasonXuDeveloper/JEngine#456]
如题。

**Comment by JasonXuDeveloper** [comment]
等bundle master支持webgl的时候je就可以无缝支持webgl

**Comment by JasonXuDeveloper** [comment]
目前JEngine理论上没多线程的东西，所以可以在webgl跑，但是ab更新模块暂时不支持webgl，但我听说现在就差加上几个宏就ok了，估计这两个月能支持
