### ISSUE TITLE
JBehaviour的Loop问题

### ISSUE THREAD

**Issue by YN1314** [JasonXuDeveloper/JEngine#469]
设置Application.targetFrameRate参数时，会影响JBehaviour的Loop的毫秒模式，似乎毫秒模式并不是一到时间就执行

**Comment by JasonXuDeveloper** [comment]
JBehaviour的循环是在这里实现的：https://github.com/JasonXuDeveloper/JEngine/blob/93e4b436a9b8eafe3c957790ffbc798325bf6d3a/UnityProject/HotUpdateScripts/JEngine/Core/JBehaviour.cs#L84

需要留意的是，这里每次循环会调用：`yield return ConstMgr.WaitFor1Sec;`。这个是Unity的函数，可能会因为设置`Application.targetFrameRate`导致频率有问题。

循环时调用上面提到的函数后才会进行`Time.realtimeSinceStartup - jb._curTime < duration`进行判断，判断通过的话则会调用JBehaviour的Loop，所以如果毫秒模式下设置的间隔特别低，确实会有这种情况
