### ISSUE TITLE
webgl平台热更新资源远程加载问题

### ISSUE THREAD

**Issue by hhxiaohei** [JasonXuDeveloper/JEngine#471]
平台:webgl
版本:unity 2020 lts

<img width="636" alt="image" src="https://github.com/JasonXuDeveloper/JEngine/assets/8379629/61ab5883-6a7e-4307-ac56-34517ff113b7">

代码:此github演示项目

热更新资源打包后放在本地http服务器,可正常访问,地址`http://127.0.0.1:5500/Bundles/WebGL/Main/`,如图
<img width="1380" alt="image" src="https://github.com/JasonXuDeveloper/JEngine/assets/8379629/3b996b0a-0bc7-4503-a113-dcadbb78d64a">

init项目配置按远程如图
<img width="534" alt="image" src="https://github.com/JasonXuDeveloper/JEngine/assets/8379629/18efada2-18c1-49e8-9467-9cbbdb93523b">

打包配置如图
<img width="794" alt="image" src="https://github.com/JasonXuDeveloper/JEngine/assets/8379629/96e0d479-2480-4873-9b0a-1b04966b4f4d">

运行后,报错如图
```
Failed to get asset bundle from web : /Users/mike/Documents/Code/u3d/JEngine/UnityProject/Assets/StreamingAssets/BuildinFiles/3d52140958b83a98ad2383d6e87f0d77.bundle Error : Cannot connect to destination host
```
<img width="1196" alt="image" src="https://github.com/JasonXuDeveloper/JEngine/assets/8379629/4b6442e4-92b6-4b35-b9b7-0ba53dc3ddf3">

但是切换到Mac平台又一切正常

**Comment by hhxiaohei** [comment]
配置的远程读取,为什么报错是从StreamingAssets读取?很奇怪

**Comment by gmhevinci** [comment]
Failed to get asset bundle from web : /Users/mike/Documents/Code/u3d/JEngine/UnityProject/Assets/StreamingAssets/BuildinFiles/3d52140958b83a98ad2383d6e87f0d77.bundle Error : Cannot connect to destination host 这个错误提示你连接本地主机失败了。在offline play mode模式下，打包测试时没问题的。如果是从CDN下载资源文件，需要WEB服务器解决跨域下载的问题。

**Comment by JasonXuDeveloper** [comment]
> Failed to get asset bundle from web : /Users/mike/Documents/Code/u3d/JEngine/UnityProject/Assets/StreamingAssets/BuildinFiles/3d52140958b83a98ad2383d6e87f0d77.bundle Error : Cannot connect to destination host 这个错误提示你连接本地主机失败了。在offline play mode模式下，打包测试时没问题的。如果是从CDN下载资源文件，需要WEB服务器解决跨域下载的问题。

OfflinePlayModeParameters在编辑器下不应该直接请求对应的StreamingAssets的文件吗，但是对应文件是存在的，不知道为什么要在编辑器下用web请求访问本地文件

**Comment by gmhevinci** [comment]
明白了。我这边切换到WEBGL平台，然后再编辑器下测试下offline play mode模式。

**Comment by hhxiaohei** [comment]
> 明白了。我这边切换到WEBGL平台，然后再编辑器下测试下offline play mode模式。

测试过 报错提示是从web加载的,应该走io加载
![074b6783f1c0ed9aadd1e9a8798c37d8](https://github.com/JasonXuDeveloper/JEngine/assets/8379629/85dd84d8-1544-48c9-8005-db7ea6eda4b4)

**Comment by gmhevinci** [comment]
编辑器切换到web gl平台，然后offline play mode 和 host play mode都测试过，没什么问题。你可以尝试把streamgAssets目录清空看看

**Comment by hhxiaohei** [comment]
https://github.com/tuyoogame/YooAsset/issues/115 参考此链接解决
