### ISSUE TITLE
关于JPrefab的bug问题

### ISSUE THREAD

**Issue by LiuZhanMingFpy** [JasonXuDeveloper/JEngine#481]
1.加载预制体时，没有正确拿到handle。无论是同步加载还是异步加载。
2.实例化两个以上的物体后，调用Dispose无法正确destory掉所有被生成到场景中的游戏对象。

**Comment by JasonXuDeveloper** [comment]
1. 同步没问题，异步已修改
2. 需要用JPrefab内置的Instantiate去实例化，不然没办法进行标记，故而没办法Destory全部被生成的对象
