### ISSUE TITLE
切换IL2Cpp API：.net 4.x JPrefab报错

### ISSUE THREAD

**Issue by whl160118** [JasonXuDeveloper/JEngine#493]
![微信截图_20230722002652](https://github.com/JasonXuDeveloper/JEngine/assets/16745827/b37fd499-6574-4682-8056-f3a48301b8d5)

**Comment by JasonXuDeveloper** [comment]
这个是热更工程配置问题，热更工程使用netframework，c#版本调8.0及以上，同时不使用mscorlib即可

**Comment by whl160118** [comment]
好的 谢谢
