### ISSUE TITLE
ChangeScene类加载DoChange找不到InitJEngine脚本的问题

### ISSUE THREAD

**Issue by donitry** [JasonXuDeveloper/JEngine#499]
![image](https://github.com/JasonXuDeveloper/JEngine/assets/8069214/1853bf79-3293-4e7a-9eb2-0877fe07bec9)
将RuntimeInitializeLoadType.BeforeSceneLoad改为AfterSceneLoad就可以了。

使用unity版本为2022.3.9  
出现问题位置为：ChangeScene类
报错内容：没有找到InitJEngine脚本，无法检验秘钥是否正确

**Comment by JasonXuDeveloper** [comment]
已修复
