### ISSUE TITLE
每次打开设置面板都特别卡

### ISSUE THREAD

**Issue by rekcah1986** [JasonXuDeveloper/JEngine#66]
rt

**Comment by JasonXuDeveloper** [comment]
请提供详细信息，比如在什么情况下，打开JEngine设置面板非常卡，例如，每次打开unity后，开启面板卡，或xxx情况下，会很卡，不然没办法排查

**Comment by JasonXuDeveloper** [comment]
老哥等你这边有消息了再reopen这个issue吧，我先给关了，因为我排查不到😂
