### ISSUE TITLE
建议：BuildAssetBundles应该与Build HotUpdateScripts.bytes分开

### ISSUE THREAD

**Issue by miuleung** [JasonXuDeveloper/JEngine#69]
rt.
看代码这两块是写在一起了，建议分开。

当资源过多而只修改更新代码时，再Build则比较消耗时间。

想知道出于什么考虑把这两项写在一块呢

ps：另外建议添加强更逻辑

**Comment by JasonXuDeveloper** [comment]
是这样的，热更代码这里视为了一种热更资源，所以与热更资源一起管理，这样打热更包的流程更简单，如果说，因为单纯一个热更dll改变了，从而需要重新打包导致耗时过长，可以考虑订阅xasset pro，集成后支持增量打AB包，不会耗时多久。
ps里的提议，强更逻辑，我不太理解，方便详细讲一下吗？

**Comment by miuleung** [comment]
> 是这样的，热更代码这里视为了一种热更资源，所以与热更资源一起管理，这样打热更包的流程更简单，如果说，因为单纯一个热更dll改变了，从而需要重新打包导致耗时过长，可以考虑订阅xasset pro，集成后支持增量打AB包，不会耗时多久。
> ps里的提议，强更逻辑，我不太理解，方便详细讲一下吗？

并没有说不把它视为一种热更资源，而是分开处理而已，这样ab包部分就不必读条，毕竟增量处理ab包也是需要读条的。

强更逻辑即是大版本强制整包更新，相对小版本（即更新资源、活动、修bug等）采取热更新这样的处理

**Comment by JasonXuDeveloper** [comment]
> > 是这样的，热更代码这里视为了一种热更资源，所以与热更资源一起管理，这样打热更包的流程更简单，如果说，因为单纯一个热更dll改变了，从而需要重新打包导致耗时过长，可以考虑订阅xasset pro，集成后支持增量打AB包，不会耗时多久。
> > ps里的提议，强更逻辑，我不太理解，方便详细讲一下吗？
> 
> 并没有说不把它视为一种热更资源，而是分开处理而已，这样ab包部分就不必读条，毕竟增量处理ab包也是需要读条的。
> 
> 强更逻辑即是大版本强制整包更新，相对小版本（即更新资源、活动、修bug等）采取热更新这样的处理

增量打ab的话，只会将更改过的资源，进行打包（例如更改过后的热更dll），这样可以节省出包时间
强更逻辑，这个是可以有，但一般游戏后台应该都有这样的控制，所以我就没有做进框架里，以后可以将这个也做出来，感谢提议

**Comment by JasonXuDeveloper** [comment]
如果还有什么需要的，再重新开此issue吧
