### ISSUE TITLE
在运行状态于classBind中点选自动获取Fields出错

### ISSUE THREAD

**Issue by miuleung** [JasonXuDeveloper/JEngine#72]
RT，此时控制台报错如下：
InvalidOperationException: This cannot be used during play mode.
UnityEditor.SceneManagement.EditorSceneManager.SaveSceneInternal (UnityEngine.SceneManagement.Scene scene, System.String dstScenePath, System.Boolean saveAsCopy) (at <1fe7a3c0284a456b9681b7a93141c89a>:0)
UnityEditor.SceneManagement.EditorSceneManager.SaveScene (UnityEngine.SceneManagement.Scene scene, System.String dstScenePath, System.Boolean saveAsCopy) (at <1fe7a3c0284a456b9681b7a93141c89a>:0)
UnityEditor.SceneManagement.EditorSceneManager.SaveScene (UnityEngine.SceneManagement.Scene scene, System.String dstScenePath) (at <1fe7a3c0284a456b9681b7a93141c89a>:0)
JEngine.Editor.ClassBindEditor+<DoConvert>d__4.MoveNext () (at Assets/Dependencies/JEngine/Editor/JEngineTools/ClassBindEditor.cs:243)

此时进度条还无法关闭，只能重新编译或重启unity解决。

可在执行前添加逻辑判断：
            if (Application.isPlaying)
            {
                EditorUtility.DisplayDialog("ClassBind Error", "This cannot be used during play mode", "OK");
                return;
            }
以此避免

**Comment by JasonXuDeveloper** [comment]
了解，请不要在运行时操作ClassBind自动获取Type，这个操作应该在非运行时使用，下个版本会解决进度条不隐藏问题

**Comment by miuleung** [comment]
> 
> 
> 了解，请不要在运行时操作ClassBind自动获取Type，这个操作应该在非运行时使用，下个版本会解决进度条不隐藏问题

另外还有一个小问题：JsonMapper转json时不支持单精度浮点数float、double的问题，转化会报错，希望JsonMapper.cs中添加转化代码。

**Comment by JasonXuDeveloper** [comment]
> > 了解，请不要在运行时操作ClassBind自动获取Type，这个操作应该在非运行时使用，下个版本会解决进度条不隐藏问题
> 
> 另外还有一个小问题：JsonMapper转json时不支持单精度浮点数float、double的问题，转化会报错，希望JsonMapper.cs中添加转化代码。

支持啊，你是哪个版本的，我做过float和double适配的，参考Scripts/Helpers/LitJsonHelper

**Comment by miuleung** [comment]
> 
> 
> > > 了解，请不要在运行时操作ClassBind自动获取Type，这个操作应该在非运行时使用，下个版本会解决进度条不隐藏问题
> > 
> > 
> > 另外还有一个小问题：JsonMapper转json时不支持单精度浮点数float、double的问题，转化会报错，希望JsonMapper.cs中添加转化代码。
> 
> 支持啊，你是哪个版本的，我做过float和double适配的，参考Scripts/Helpers/LitJsonHelper

我用最新版v0.6.1。不是AppDomain的注册，是JsonMapper中没添加注册代码

**Comment by JasonXuDeveloper** [comment]
> > > > 了解，请不要在运行时操作ClassBind自动获取Type，这个操作应该在非运行时使用，下个版本会解决进度条不隐藏问题
> > > 
> > > 
> > > 另外还有一个小问题：JsonMapper转json时不支持单精度浮点数float、double的问题，转化会报错，希望JsonMapper.cs中添加转化代码。
> > 
> > 
> > 支持啊，你是哪个版本的，我做过float和double适配的，参考Scripts/Helpers/LitJsonHelper
> 
> 我用最新版v0.6.1。不是AppDomain的注册，是JsonMapper中没添加注册代码

不是，我没JsonMapper里写，但是JsonMapper有个方法用于转换类型，所以在注册LitJson的地方我写了个注册double,float这种

**Comment by miuleung** [comment]
> 
> 
> > > > > 了解，请不要在运行时操作ClassBind自动获取Type，这个操作应该在非运行时使用，下个版本会解决进度条不隐藏问题
> > > > 
> > > > 
> > > > 另外还有一个小问题：JsonMapper转json时不支持单精度浮点数float、double的问题，转化会报错，希望JsonMapper.cs中添加转化代码。
> > > 
> > > 
> > > 支持啊，你是哪个版本的，我做过float和double适配的，参考Scripts/Helpers/LitJsonHelper
> > 
> > 
> > 我用最新版v0.6.1。不是AppDomain的注册，是JsonMapper中没添加注册代码
> 
> 不是，我没JsonMapper里写，但是JsonMapper有个方法用于转换类型，所以在注册LitJson的地方我写了个注册double,float这种

我的意思是JsonMapper的转换类型注册方法中没有覆盖完整double,float的数据类型。具体你可以试一下是否转换出错

**Comment by JasonXuDeveloper** [comment]
> > > > > > 了解，请不要在运行时操作ClassBind自动获取Type，这个操作应该在非运行时使用，下个版本会解决进度条不隐藏问题
> > > > > 
> > > > > 
> > > > > 另外还有一个小问题：JsonMapper转json时不支持单精度浮点数float、double的问题，转化会报错，希望JsonMapper.cs中添加转化代码。
> > > > 
> > > > 
> > > > 支持啊，你是哪个版本的，我做过float和double适配的，参考Scripts/Helpers/LitJsonHelper
> > > 
> > > 
> > > 我用最新版v0.6.1。不是AppDomain的注册，是JsonMapper中没添加注册代码
> > 
> > 
> > 不是，我没JsonMapper里写，但是JsonMapper有个方法用于转换类型，所以在注册LitJson的地方我写了个注册double,float这种
> 
> 我的意思是JsonMapper的转换类型注册方法中没有覆盖完整double,float的数据类型。具体你可以试一下是否转换出错

毫无问题。
测试环境：Master和Development分支，
测试代码：
```c#
namespace HotUpdateScripts
{
    public class TestJ
    {
        public float f;
        public double d;

        public override string ToString()
        {
            return $"f:{f}, d:{d}";
        }
    }

    public static class Program
    {
        public static void RunGame()
        {
            var j = new TestJ();
            j.f = 1.23f;
            j.d = 0.102934875d;

            var s = JsonMapper.ToJson(j);
            Debug.Log(s);

            var newJ = JsonMapper.ToObject<TestJ>(s);
            Debug.Log(newJ);
        }
    }
}
```
控制台输出：
{"f":"1.23","d":0.102934875}

==========ILRuntime StackTrace==========
IL_0029: call System.Void UnityEngine.Debug::Log(System.Object)
at HotUpdateScripts.Program.RunGame() /Users/jason/Documents/GitHub/JEngine/UnityProject/HotUpdateScripts/Program.cs:Line 55


f:1.23, d:0.102934875

==========ILRuntime StackTrace==========
IL_0037: call System.Void UnityEngine.Debug::Log(System.Object)
at HotUpdateScripts.Program.RunGame() /Users/jason/Documents/GitHub/JEngine/UnityProject/HotUpdateScripts/Program.cs:Line 58
```

我不知道你遇到的问题是什么，我很久以前就适配过Single和Double类型，除非你的LitJson用的不是JEngine自带的，或者你用的是老版本的。

**Comment by miuleung** [comment]
Quote折叠太多，直接回复好了。
你上述例子毫无疑问是没有问题的。但你是否测试过直接读取第三方json解析？包括网络返回json或直接读取本地json字符串。

Json字符串：

>```cs
> private static string strTest =
>        "{\"temperature\": 24.6,\"temperatureDiff\": 0.3,\"airpressure\": 1006.0,\"humidity\": 54.0,\"rain\": 0.0,\"rcomfort\": >65,\"icomfort\": 0,\"info\": \"晴\",\"img\": \"0\",\"feelst\": 21.9}";
>```

数据结构：
>```cs
> [System.Serializable]
>     public class Weather //天气
>     {
>         public float temperature; //温度
>         public float temperatureDiff; //温差
>         public float airpressure; //大气压
>         public float humidity; //湿度
>         public float rain; //降雨量
>         public int rcomfort; //舒适度
>         public int icomfort;
>         public string info; //天气 - 晴
>         public string img; // Icon 下标
>         public float feelst; //体感温度
>     }
>```

你试试解析这段Json，这是中央气象台官网提供的api返回的json其中的一段，url为http://www.nmc.cn/f/rest/real/59493
//59493为深圳城市代码，获取方式为Get

此时会获得错误：
>JsonException: Can't assign value '24.6' (type System.Double) to type System.Single

而解决方案：
>https://www.pianshen.com/article/763049829/


以上是我遇到的问题，希望我说的明白了

**Comment by JasonXuDeveloper** [comment]
你说没覆盖单双浮点类型转换，所以我给你来了个例子，然而你给我的例子是双浮点转单浮点，你之前自己没说清楚-_-||
你的解决方案我也看了，就是在注册一个单浮点和双浮点的互转，这个你在我n天前给你说的Json注册器里加一行就好啊😂

**Comment by JasonXuDeveloper** [comment]
我注册器模板也提供了，我也不可能把几十种类型的注册转换全写进去，所以这种时候你就得根据自己的项目自己往注册器里加规则啊
