### ISSUE TITLE
关于JBehaviour生命周期的问题

### ISSUE THREAD

**Issue by hatepudge** [JasonXuDeveloper/JEngine#74]
请问JBehaviour如何实现 类似MonoBehaviour的OnEnable 和 OnDisable跟随物体active变化可多次调用的机制？

**Comment by JasonXuDeveloper** [comment]
JBehaviour没有这个，以后可能会加入
JBehaviour为了轻量，gameObject可理解为只是一个字段，想用的时候获取，并没有跟着gameObject的状态来定周期之类的方法

**Comment by hatepudge** [comment]
好的 谢谢。

**Comment by JasonXuDeveloper** [comment]
嗯嗯，以后可能会制作一个函数用于监听这个事件
