### ISSUE TITLE
编辑器运行正常，打包后运行，出现空引用报错

### ISSUE THREAD

**Issue by miuleung** [JasonXuDeveloper/JEngine#76]
RT，但貌似功能都没影响。

重现步骤：
Touch To Start-UI Demo 即会出现十多个空引用报错。

内容为两种：

>![Exception]->NullReferenceException
> ->MonoBehaviourAdapter+Adaptor+<Awake>d__19.MoveNext () (at <ab598dd3b745488fad8b77b37557ecf5>:0)
>--- End of stack trace from previous location where exception was thrown ---
>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
>System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at ><9577ac7a62ef43179789031239ba8798>:0)
>UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e3cc0d511c49480aba0b4b05faed2ad3>:0)
>UnityEngine.UnitySynchronizationContext:ExecuteTasks()

>-----------------------------------------------------------------------------------------------------------

>![Exception]->NullReferenceException
> ->ProjectAdapter.ExampleAPIAdapter+Adapter+<Awake>d__13.MoveNext () (at <ab598dd3b745488fad8b77b37557ecf5>:0)
>--- End of stack trace from previous location where exception was thrown ---
>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
>System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at ><9577ac7a62ef43179789031239ba8798>:0)
>UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e3cc0d511c49480aba0b4b05faed2ad3>:0)
>UnityEngine.UnitySynchronizationContext:ExecuteTasks()

报错出现在“初始化 UIRootView成功”Log之前。

是否跟此issue有关联呢？
https://github.com/Ourpalm/ILRuntime/issues/246

**Comment by miuleung** [comment]
另外还有一处小BUG：
每次启动检查资源版本号时，UpdateScreen中Versions.LoadVersion中路径不完整（中间缺少了DLC字段）导致每次启动都只会取-1，导致了无论资源已经更新了多少次，启动后资源版本号都是显示的-1

**Comment by JasonXuDeveloper** [comment]
看报错，是跨域适配器的问题，感觉像是初始化适配器的时候出现的null错误，我回去排查一下的，另外，这个错误发生在哪个版本？

**Comment by miuleung** [comment]
> 看报错，是跨域适配器的问题，感觉像是初始化适配器的时候出现的null错误，我回去排查一下的，另外，这个错误发生在哪个版本？

v0.6.1

**Comment by JasonXuDeveloper** [comment]
> > 看报错，是跨域适配器的问题，感觉像是初始化适配器的时候出现的null错误，我回去排查一下的，另外，这个错误发生在哪个版本？
> 
> v0.6.1

好的，下次更新的时候提交修复

**Comment by JasonXuDeveloper** [comment]
问题已修复

**Comment by JasonXuDeveloper** [comment]
在dev分支，master分支0.6.2再合并
