### ISSUE TITLE
classbind的gameobject无法播放animator（无法位移）

### ISSUE THREAD

**Issue by kkmjnh11110** [JasonXuDeveloper/JEngine#87]
举例：
这个对象本来要挂载一个触发器，并且classbind一个脚本做触发事件

解决方法：
创建一个子对象，子对象下添加一个触发器，并且classbind一个脚本做触发事件

**Comment by kkmjnh11110** [comment]
//这个脚本 classbind到role（gameobject）上（需要组件：BoxCollider+sprite）
namespace HotUpdateScripts.Scripts.Battle
{
    using UnityEngine;

    public class Skill : MonoBehaviour
    {
        private GameObject _skill;

        private void Awake()
        {
            _skill = transform.GetChild(0).gameObject;
        }

        void OnMouseUp()
        {
            PlaySkillAnimator();
        }

        /// <summary>
        /// 播放动画.
        /// </summary>
        private void PlaySkillAnimator()
        {
            _skill.GetComponent<Animator>().Play("guanYu");
        }
    }
}

//这个脚本挂载在role的子对象skill上（需要组件：BoxCollider2d+animator（做个位移动画））
// ------------------------------------------------------------------------------
// Copyright (c) 2018-2019 Beijing Bytedance Technology Co., Ltd.
// All Right Reserved.
// Unauthorized copying of this file, via any medium is strictly prohibited.
// Proprietary and confidential.
// ------------------------------------------------------------------------------
namespace HotUpdateScripts.Scripts.Battle
{
    using UnityEngine;

    public class SkillCollider : MonoBehaviour
    {
        private void OnTriggerEnter2D(Collider2D collision)
        {
            print("1");
        }
    }
}

**Comment by JasonXuDeveloper** [comment]
复现了，可以通过代码控制播放，试试master
