### ISSUE TITLE
关于热更的一个疑问

### ISSUE THREAD

**Issue by huangkumao** [JasonXuDeveloper/JEngine#88]
请问如果要将热更的内容加入首包现在是否支持? 就是第一次发包玩家不需要进行大量更新, 将现在生成的DLC目录放到安装包里, 后续可以通过热更更新内容.

**Comment by JasonXuDeveloper** [comment]
支持，菜单栏，有选项，Copy to Streaming Assets suggests for iOS，
这个就是为了ios审核做的，热更进首包

**Comment by huangkumao** [comment]
OK 谢谢, 建议您在相关文档里面能够说明一下

**Comment by JasonXuDeveloper** [comment]
好的，没问题
