### ISSUE TITLE
DLC上传远程服务器更新后每次都会报一个错

### ISSUE THREAD

**Issue by huangkumao** [JasonXuDeveloper/JEngine#89]
代码是git上的代码
![2021412-114849](https://user-images.githubusercontent.com/10599192/114338275-542b1f80-9b85-11eb-9bfa-a189cf7d113b.png)
EndOfStreamException: Unable to read beyond the end of the stream.
System.IO.BinaryReader.FillBuffer (System.Int32 numBytes) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.BinaryReader.ReadInt32 () (at <9577ac7a62ef43179789031239ba8798>:0)
libx.Versions.LoadVersion (System.String filename) (at Assets/Dependencies/XAsset/Runtime/Core/Versions.cs:122)
UnityEngine.Debug:LogException(Exception)
libx.Versions:LoadVersion(String) (at Assets/Dependencies/XAsset/Runtime/Core/Versions.cs:130)
libx.<RequestVersions>d__34:MoveNext() (at Assets/Dependencies/XAsset/Runtime/Core/Updater.cs:474)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by JasonXuDeveloper** [comment]
可以更新dev分支，这个问题在dev分支修复了
