### ISSUE TITLE
GetPlatformForAssetBundles 这个函数的问题

### ISSUE THREAD

**Issue by huangkumao** [JasonXuDeveloper/JEngine#90]
我感觉应该改成这样, 现在的宏定义会导致发包以后找不到路径, 宏定义外面少了return null

        private static string GetPlatformForAssetBundles(RuntimePlatform target)
        {
#if UNITY_EDITOR
            var t = EditorUserBuildSettings.activeBuildTarget;
            switch (t)
            {
                case BuildTarget.Android:
                    return "Android";
                case BuildTarget.iOS:
                    return "iOS";
                case BuildTarget.WebGL:
                    return "WebGL";
                case BuildTarget.StandaloneWindows:
                case BuildTarget.StandaloneWindows64:
                    return "Windows";
                case BuildTarget.StandaloneOSX:
                    return "OSX";
            }
#else
            switch (target)
            {
                case RuntimePlatform.OSXEditor:
                case RuntimePlatform.OSXPlayer:
                    return "OSX";
                case RuntimePlatform.WindowsPlayer:
                case RuntimePlatform.WindowsEditor:
                    return "Windows";
                case RuntimePlatform.IPhonePlayer:
                    return "iOS";
                case RuntimePlatform.Android:
                    return "Android";
                default:
                    return null;
            }
#endif
            return null;

**Comment by JasonXuDeveloper** [comment]
默认的有的，可以看看详细的代码，他区分了编辑器和真机，其中编辑器才会用到宏，而且都是default return null
```

#if UNITY_EDITOR
            var t = EditorUserBuildSettings.activeBuildTarget;
            switch (t)
            {
                case BuildTarget.Android:
                    return "Android";
                case BuildTarget.iOS:
                    return "iOS";
                case BuildTarget.WebGL:
                    return "WebGL";
                case BuildTarget.StandaloneWindows:
                case BuildTarget.StandaloneWindows64:
                    return "Windows";
#if UNITY_2017_3_OR_NEWER
                case BuildTarget.StandaloneOSX:
                    return "OSX";
#else
                case BuildTarget.StandaloneOSXIntel:
                case BuildTarget.StandaloneOSXIntel64:
                case BuildTarget.StandaloneOSXUniversal:
                    return "OSX";
#endif
                default:
                    return null;
            }
#endif

```

**Comment by huangkumao** [comment]
这个函数再真机上面没有返回值 #if UNITY_EDITOR 这个条件包含了所有的代码, 1: 导致真机这个是空函数, 2: 导致有的情况下这个函数没有返回值, 群里有人也抱了这个错误, 需要再最后加一个return null;才行, 可能是用了2020的原因 但是当#if UNITY_EDITOR 这个不生效的时候 这个函数确实没有返回值

**Comment by huangkumao** [comment]
按我改的之后 就没问题了

**Comment by JasonXuDeveloper** [comment]
ok，感谢提醒

**Comment by JasonXuDeveloper** [comment]
已在dev分支修复，等合并

**Comment by huangkumao** [comment]
android 下面还是有问题.... 宏定义有问题 安卓下面返回会返回null

**Comment by JasonXuDeveloper** [comment]
dev分支才更新了
