### ISSUE TITLE
首包自带热更资源不成功

### ISSUE THREAD

**Issue by gamebbq** [JasonXuDeveloper/JEngine#91]
**iOS,安卓和本地编辑器环境下均不成功.**
iOS的问题是拷贝目录下没有res,且dlc中的其它文件全进去了.
安卓的问题是拷贝目录下(res和ver都有)似乎没有问题,但不成功.

**Comment by gamebbq** [comment]
![6B5E92498F0305D765A17282266434C4](https://user-images.githubusercontent.com/82456884/114566174-98f9a800-9ca4-11eb-848d-6f1a4a3bcfe0.jpg)
iOS下的拷贝目录截图

**Comment by JasonXuDeveloper** [comment]
已修复，等合并

**Comment by JasonXuDeveloper** [comment]
有点小问题，需要重新修改

**Comment by JasonXuDeveloper** [comment]
已修复，用dev分支或等0.6.2即可
