### ISSUE TITLE
提个UI框架的小建议

### ISSUE THREAD

**Issue by huangkumao** [JasonXuDeveloper/JEngine#92]
APanelBase       
        public bool IsPlayOpenSound = true;
        public bool IsPlayCloseSound = true;
        public bool IsPlayButtonSound = true;
        public bool isFilm = false;
        public bool m_IsKeepOpen = false;
        public bool m_IsLoadFromResources = false;
        public bool m_IsAlwaysOpen = false;
        public bool NeedAnchor = false;//刘海屏幕适配
        public UIPanelType m_Type = UIPanelType.Two;

        public string m_strPanelViewName = null;
        public GameObject m_gameobj = null;
        public RectTransform Trans = null;
        public Action<APanelBase> OnCloseEvent = null;
        public Action<APanelBase> OnOpenEvent = null;
        public static Vector3 HidePos = Vector3.left * 10000.0f;
        private Vector3 _srcLocalPos;

        public bool m_IsAffectMusic = false;//是否影响声音
        public bool m_IsResetMusic = false;//是否还原声音

这里面很多值没有使用, 也没有注释, demo里面也没有用到, 希望能通过或者注释说明一下,

UIMgr
    里面提供的接口跟参数也没有注释跟使用说明, 
   eg: public void ShowUI(string uibaseName, bool isSaveShow = false,
isSaveShow 是什么含义?

**Comment by huangkumao** [comment]
希望0.6.2里面能多提供一些UI的demo跟用法

**Comment by huangkumao** [comment]
晚上测试了一下 这个UI系统bug好多.... 随便举几个例子
UIUtility.BindClickEvent(Trans, "Btn", OnClick);
使用上面这种方式绑定的事件 效率超级底, 点了延迟好久才有反应, 而且连续快速点击按钮就没有事件反应了....

m_Btn.onClick.AddListener(() =>  像这样自己添加回调就好了 没问题了


还有 UIUtility的 public static T GetComponent<T>(RectTransform trans, string name) where T : Component
这个函数也有明显bug 需要像下面这么写
            if (trans == null)
                return null;

            if (Trans.ContainsKey(trans))
            {
                if (Trans.Values.SelectMany(v => v.Keys).Contains(name))
                {
                    return (T)Trans[trans][name];
                }
            }
            else
            {
                Trans.Add(trans,
                    new Dictionary<string, Component>(1));
            }

            RectTransform findTrans = Control(name, trans);

            if (!CheckComponent(findTrans, trans.name, name))
            {
                return null;
            }

            var f = findTrans.GetComponent<T>();
            Trans[trans].Add(name, f);
            return f;

还有用这种方式 UIMgr.Instance.ShowUI("UITest"); 打开一个UI效率也很低, 一个空UI都要将近1秒钟才能显示出来, 而且android上面还显示不出来.... 暂时不知道啥原因

感觉现在的UI框架还没法直接用啊

**Comment by JasonXuDeveloper** [comment]
跟着demo用吧，用法有问题。。
showUI慢因为他得加在热更资源啊

**Comment by JasonXuDeveloper** [comment]
有不懂ui框架的地方直接问群里的lfone

**Comment by JasonXuDeveloper** [comment]
base.setObj(obj);
这个不能删

**Comment by JasonXuDeveloper** [comment]
你删了都是bug正常

**Comment by huangkumao** [comment]
OK 我在试试, demo里例子太少了,很多参数接口都没用到, 我了你的视频 里面其实没用到这个UI框架, 我也在思考做个小游戏是否需要这么大的框架

**Comment by JasonXuDeveloper** [comment]
热更工程的东西没必要用，都是按需使用的，功能摆在那，是否要用取决于你的哈哈
本地工程的东西才是必备的

**Comment by huangkumao** [comment]
OK 明白了 我自己封装一个简单的UI框架得了 反正小游戏就那几个UI无所谓

**Comment by JasonXuDeveloper** [comment]
嗯是这个意思，热更工程的源码要用啥就用啥就好

**Comment by bournes** [comment]
我在做卡牌游戏，UI假面有90多个。。想要一个好用的UIkit..

**Comment by JasonXuDeveloper** [comment]
> 我在做卡牌游戏，UI假面有90多个。。想要一个好用的UIkit..

推荐QFramework 很强大的UI框架
