### ISSUE TITLE
2个Class Bind的问题

### ISSUE THREAD

**Issue by huangkumao** [JasonXuDeveloper/JEngine#93]
![001](https://user-images.githubusercontent.com/10599192/115050224-1f64f280-9f0e-11eb-9968-2840bde796c3.png)
![002](https://user-images.githubusercontent.com/10599192/115050235-21c74c80-9f0e-11eb-9572-3d2e6a7faad0.png)

Unity 2020.3.3
原始工程打开
点 自动获取fields 第一个错
点 自动获取type 第二个错 - 做成prefab的情况下

**Comment by JasonXuDeveloper** [comment]
已修复，等合并
