### ISSUE TITLE
自动获取fields时出现的问题

### ISSUE THREAD

**Issue by gamebbq** [JasonXuDeveloper/JEngine#94]
在脚本中删除之前已绑定的对象后，删除Bind面板的对象，然后点击自动获取fields仍然会被再次获取到，相关Fields无法被正确更新。保存或编译都没用，只能是在unity中先run一波游戏之后，相关的新Bind状态才会被更新（删掉的绑定对象才不会被自动获取到）。

**Comment by JasonXuDeveloper** [comment]
ClassBind无法在运行时生效啊

**Comment by JasonXuDeveloper** [comment]
> 在脚本中删除之前已绑定的对象后，删除Bind面板的对象

是什么意思

**Comment by gamebbq** [comment]
具体是这样的，比如脚本里有bind一个gameobject，之后发现不需要，就把它在脚本里删掉了，然后回到Bind面板里把绑定的这个对象也删掉(因为自动获取只能获取新增不能获取到删除)。这时候如果再点自动获取，这个已经删掉的对象又会出现在Bind面板里.

**Comment by JasonXuDeveloper** [comment]
热更工程编译，unity控制台输出convert dll in xx ms后再点自动转换就好，编译热更dll和转换需要时间
