### ISSUE TITLE
关于ClassBind的一个导致Unity运行崩溃的bug

### ISSUE THREAD

**Issue by huangkumao** [JasonXuDeveloper/JEngine#95]
有A,B两个热更脚本, 均通过ClassBind绑定在场景GameObject上面
A脚本有个gameobject变量 通过ClassBind引用了B的gameobject
在A脚本Awake方法里使用  Object.Instantiate(B的gameobj, 会导致Unity编辑器直接崩溃
如果在Start方法里使用 那么就没有问题.

**Comment by huangkumao** [comment]
![Uploading 11111111111.png…]()

**Comment by JasonXuDeveloper** [comment]
已在dev修复
