### ISSUE TITLE
RepeatUntil 语法问题

### ISSUE THREAD

**Issue by Lin-CH** [JasonXuDeveloper/JEngine#96]
bool condition = false;
            JAction repeatWhenJ = new JAction();
            repeatWhenJ.RepeatUntil(() =>
            {
                Debug.Log("????");
            }, () => condition = false, 1)
            .ExecuteAsync(true);

            JAction delayJ = new JAction();
            delayJ.Do(() => Debug.Log("JAction 在执行！用了延时Delay"))
                .Delay(3)
                .Do(() => Debug.Log("延时了3秒钟??????????"))
                .Do(() => condition = false)
                .Execute();

不知道为什么上面代码 condition变成false 但是循环还在继续跑

**Comment by JasonXuDeveloper** [comment]
找到问题了，你ExecuteAsync，没await也没弃元，导致线程同步了，出了问题。
代码写成：
```
bool condition = false;
            JAction repeatWhenJ = new JAction();
            _= repeatWhenJ.RepeatUntil(() =>
            {
                Debug.Log("????");
            }, () => condition = false, 1)
            .ExecuteAsync(true);


            JAction delayJ = new JAction();
            delayJ.Do(() => Debug.Log("JAction 在执行！用了延时Delay"))
                .Delay(3)
                .Do(() => Debug.Log("延时了3秒钟??????????"))
                .Do(() => condition = false)
                .Execute();
```
重点是那个_= repeatWhenJ.ExecuteAsync(true)
不等待的话别Async。。

**Comment by JasonXuDeveloper** [comment]
不是弃元问题，是condition问题，()=> condition = false是赋值操作，永远返回true的，没办法终止，要()=>condition == false
